version: "3.9"
    
services:
  node1-bootnode:
    build:
      context: ./node1-bootnode
    networks:
      - bridged-network-1
    image: geth-docker-node1-bootnode
    restart: always

  node2-miner:
    depends_on:
      - node1-bootnode
    build:
      context: ./node2-miner
    networks:
      - bridged-network-1
    image: geth-docker-node2-miner
    restart: always
    
  node3-rpc:
    depends_on:
      - node1-bootnode
      - node2-miner
    build:
      context: ./node3-rpc
    networks:
      - bridged-network-1
    image: geth-docker-node3-rpc
    restart: always

networks:
  bridged-network-1:
    driver: bridge
